### PR TITLE
Updated GPhL Qt4 docker, and moved GPhL dockers to own directory

### PR DESCRIPTION
**Pull request by rhfogh**
Added GPhL docker changes, updated GPhL docker to inherit from std dev docker ionstead of replacing it.

Also set up so *no* HO, hardware repository, user information etc. is set in the docker (set in the start file instead) for Qt4

### CODE REVIEW

**Comment by jordiandreu** [comment]
It is fine for me, however I have no permissions to accept the PR.

**Comment by IvarsKarpics** [comment]
Hi @jordiandreu ,

I added you to the collaborator list. You should be now able to merge the PR

**Comment by jordiandreu** [comment]
Back from holidays, thanks @IvarsKarpics.

**Comment by jordiandreu** [comment]
Thanks for coding!

**Pull request merged**
